language: python
python:
- '2.7'
install:
- pip install .
- pip install pytest --upgrade
- pip install -r requirements.txt
script:
- py.test tests
env:
  global:
  - API_CHECK=https://appengine.google.com/api/updatecheck
  - GAE=./google_appengine
before_script:
- SDK_VERSION=1.9.49
- SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/google_appengine_$SDK_VERSION.zip
- wget $SDK_URL -nv
- unzip -q google_appengine_$SDK_VERSION.zip
deploy:
  provider: pypi
  user: herrkaste
  password:
    secure: ojCKKNV+oVYJTlsgQQTOYfffjCdz5QIi2gVOLxIYpOp+DVVvVV1xy4G2yZ8aWWCRUWiHslcEIIg0KiuJUz+gEfoNB1ORVfHI7FhoZiL2Xbq5h1Sga+3FHdB3c4OGTe7O0/c++RBdiLI9xbSFQpshKtWPmofNovDNAdqBszU392J41wRqJzh0EarMNjb9+FWxK4GHcZfNXHH98ylsp4Ar6ji0NGw7RQXjYZZ7u0nm4oc6naYRCx5eoC3/66Ukx5nKHrR5OsxzgWhrSVdkYt3Yt/GXTymXDqH/+uGaT0WwQPyFW1Hltl1S23RGbwBkOXBDfY1fZHeDf57s2d/J05FyUoYwas4Z7X+aYwVhbR6zV5t9/mMBUIPMThqzZfdCIfmb0x4d6/M2AZKiz0YC0gT5hINm4AsYuAKn7nkecCwhRuIgrudt6RiRdVG+ThVLdAkSd53D9bpDZALrMsNLJdmuf/BMyR/q/Db/o9Tsubtt2pLSIJAzkx6jp361jJ802tnwi0JuwQA55W9BfYZsBSfQDb8vuN3HuqUqGCoSS2eVR0PHI80C9R1+LSWKg5U/ndxA1e8BJjk45G5tna+e5GxByjB0ndQ6idLVswVhdqQWgK5wKM5LbTGM0e0Kij+K4fSO42Y8t2qgGRB3b9eN3mf0m/aQhiBT1PqHvqXteVM8Ezk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: kaste/deferred2
